Extracted: traps to bash_setup repo

diff --git a/bin/megauni b/bin/megauni
--- a/bin/megauni
+++ b/bin/megauni
@@ -25,13 +25,13 @@ export RACK_ENV="production"
 
 # ==============================================================
 GREEN=$(tput setaf 2)
+RED='\e[0;31m'
+RESET_COLOR=$(tput sgr0)
 GREEN_BG=$(tput setb 2)
 WHITE=$(tput setaf 7)
 BOLD_WHITE_ON_GREEN=$(tput bold)${WHITE}${GREEN_BG}
 BOLD_WHITE=$(tput bold)${WHITE}
-RESET_COLOR=$(tput sgr0)
 ORANGE='\e[0;33m'
-RED='\e[0;31m'
 BG_RED='\e[1;31m'
 # ===============================================
 
@@ -332,7 +332,7 @@ case "$action" in
     if [[ "$@" =~ 'watch' && "$1" == "watch" ]]; then
       watch="true"
       shift
-      echo "=== Watching $(basename $0) (proc group $$): $@"
+      echo "=== Watching $(basename $0) (proc $$): $@"
     fi
 
     if [[ ! -z "$@" && "$1" == "reset" ]]; then
@@ -425,78 +425,70 @@ case "$action" in
     fi
     ;;
 
-  "watch_files")
-    echo -e "=== Watching ${BOLD_WHITE}$(basename $0)${RESET_COLOR}    (proc group $$)..."
-      while read CHANGE
-      do
-        dir=$(echo "$CHANGE" | cut -d' ' -f 1)
-        op=$(echo "$CHANGE" | cut -d' ' -f 2)
-        file=$(echo "$CHANGE" | cut -d' ' -f 3)
-        path="${dir}$file"
+  "__watch")
+    eval "$(bash_setup setup_traps)"
+    setup_traps
 
-        echo -e "=== $CHANGE ($path)"
+    echo -e "=== Watching ${BOLD_WHITE}$(basename $0)${RESET_COLOR}    (proc $$)..."
+    while read CHANGE
+    do
+      dir=$(echo "$CHANGE" | cut -d' ' -f 1)
+      op=$(echo "$CHANGE" | cut -d' ' -f 2)
+      file=$(echo "$CHANGE" | cut -d' ' -f 3)
+      path="${dir}$file"
 
-        if [[ ! -z "$file" ]]; then
+      echo -e "=== $CHANGE ($path)"
 
-          if [[ "$path" == *bin/megauni* ]]; then
-            echo ""
-            echo "=== ${GREEN}Reloading${RESET_COLOR} this script: $0 ${script_args[@]}"
-            exec $0 ${script_args[@]}
-          fi
+      if [[ ! -z "$file" ]]; then
 
-          if [[ "$file" =~ ".styl" ]]; then
-            bin/megauni stylus "$path"
-          fi
-
-          if [[ ! -f logs/rendering ]]; then # ========
-            if [[ "$file" =~ "markup.rb" ]]; then
-              bin/megauni render "$path" || rb_failed="$path"
-            else
-              # Most likely a base file, so all files have to be re-rendered:
-              if [[ "$path" =~ "applets" && "$path" =~ ".rb" ]]; then
-                render_all
-              fi
-            fi
-
-
-            if [[ "$file" =~ "markup.html" ]]; then
-              bin/megauni restart
-            fi
-
-          fi # if ! -f logs/rendering =================
-
-          if [[ "$file" =~ ".js" ]]; then
-            if [[ "$path" =~ "Public/"  ]]; then
-              echo -n "=== Running jshint: "
-              ( bin/megauni jshint $path && echo -e "${GREEN}Passed${reset_color}" ) || js_failed=""
-            else
-              bin/megauni restart
-            fi
-          fi
-
+        if [[ "$path" == *bin/megauni* ]]; then
+          echo ""
+          echo "=== ${GREEN}Reloading${RESET_COLOR} this script: $0 ${script_args[@]}"
+          exec $0 ${script_args[@]}
         fi
 
-        echo ""
-      done < <(inotifywait --quiet --monitor --event close_write --exclude "/.git/|/logs/|/Public/(\?\!applets)/|/node_modules/" -r ./)
+        if [[ "$file" =~ ".styl" ]]; then
+          bin/megauni stylus "$path"
+        fi
+
+        if [[ ! -f logs/rendering ]]; then # ========
+          if [[ "$file" =~ "markup.rb" ]]; then
+            bin/megauni render "$path" || rb_failed="$path"
+          else
+            # Most likely a base file, so all files have to be re-rendered:
+            if [[ "$path" =~ "applets" && "$path" =~ ".rb" ]]; then
+              render_all
+            fi
+          fi
+
+
+          if [[ "$file" =~ "markup.html" ]]; then
+            bin/megauni restart
+          fi
+
+        fi # if ! -f logs/rendering =================
+
+        if [[ "$file" =~ ".js" ]]; then
+          if [[ "$path" =~ "Public/"  ]]; then
+            echo -n "=== Running jshint: "
+            ( bin/megauni jshint $path && echo -e "${GREEN}Passed${reset_color}" ) || js_failed=""
+          else
+            bin/megauni restart
+          fi
+        fi
+
+      fi
+
+      echo ""
+    done < <(inotifywait --quiet --monitor --event close_write --exclude "/.git/|/logs/|/Public/(\?\!applets)/|/node_modules/" -r ./)
     ;;
 
   "watch")
 
+    eval "$(bash_setup setup_traps)"
+    setup_traps
+
     use_server="$([[ "$@" =~ "no_server" ]] && echo "" || echo "yes" )"
-
-    on_exit () {
-      echo ""
-      if [[ -n "$use_server" ]] ; then
-        echo "=== ${GREEN}Waiting${RESET_COLOR} for proc group: ${$}..."
-        $0 stop
-        wait
-        echo "=== ${GREEN}Done${RESET_COLOR} ($(basename $0) $$)"
-      else
-        wait
-      fi
-    }
-
-    trap 'on_exit' EXIT
 
     if [[ "$@" == *test* ]]; then
       shift
@@ -508,11 +500,12 @@ case "$action" in
     re='^[0-9]+$'
     # === Start server:
 
+    echo -e "=== $(basename $0): Proc: $$ Proc Group: $(bash_setup proc_group $$)"
     if [[ -n "$use_server" ]]; then
-      ( bin/megauni watch_files ) &
+      ( bin/megauni __watch ) &
       bin/megauni restart --no-daemon
     else
-      bin/megauni watch_files
+      bin/megauni __watch
     fi
 
     ;;
