Started: client-side implementation

diff --git a/bin/megauni b/bin/megauni
--- a/bin/megauni
+++ b/bin/megauni
@@ -25,6 +25,7 @@ export RACK_ENV="production"
 
 # ==============================================================
 # http://www.ibm.com/developerworks/aix/library/au-learningtput/
+green=$(tput setaf 2)
 green_bg=$(tput setb 2)
 white=$(tput setaf 7)
 bold_white_on_green=$(tput bold)${white}${green_bg}
@@ -453,6 +454,12 @@ case "$action" in
     # === Render all stylus files:
     bin/megauni render_stylus
 
+    for f in ./Public/applets/*/script.js
+    do
+      echo "=== JSHint: $f"
+      bin/megauni jshint "$f"
+    done
+
     cleanup () {
       bin/megauni stop
       # echo -e "\n=== Please wait... shutting down server..."
@@ -527,7 +534,7 @@ case "$action" in
           bin/megauni stylus "$path"
         fi
 
-        if [[ ! -f logs/rendering ]]; then
+        if [[ ! -f logs/rendering ]]; then # ========
           if [[ "$file" =~ "markup.rb" ]]; then
             bin/megauni render "$path" || rb_failed="$path"
           else
@@ -542,12 +549,12 @@ case "$action" in
             bin/megauni restart
           fi
 
-        fi # if ! -f logs/rendering
+        fi # if ! -f logs/rendering =================
 
         if [[ "$file" =~ ".js" ]]; then
-          if [[ "$file" =~ "Public/"  ]]; then
-            echo "=== Running jshint:"
-            bin/megauni jshint $path || js_failed=""
+          if [[ "$path" =~ "Public/"  ]]; then
+            echo -n "=== Running jshint: "
+            ( bin/megauni jshint $path && echo -e "${green}Passed${reset_color}" ) || js_failed=""
           else
             bin/megauni restart
           fi
