Touchup: bin/megauni

diff --git a/bin/megauni b/bin/megauni
--- a/bin/megauni
+++ b/bin/megauni
@@ -439,9 +439,24 @@ case "$action" in
     done
     ;;
 
-  "__watch")
+  "spec_file")
     last_opt=$(echo $@ | tr -s ' ' | rev | cut -d' ' -f 1 | rev)
     next_to_last_opt=$(echo $@ | tr -s ' ' | rev | cut -d' ' -f 2 | rev)
+    spec_file=''
+    if [[ -n "$next_to_last_opt" && -n "$last_opt" ]]; then
+      spec_file=$(echo Server/$next_to_last_opt/specs/*-${last_opt}.js)
+      if [[ ! -f "$(echo $spec_file | cut -d' ' -f 1)" ]]; then
+        spec_file=''
+      fi
+    fi
+    echo $spec_file
+    ;;
+
+  "__watch")
+    spec_file="$($0 spec_file $@)"
+    if [[ -n "$spec_file" ]]; then
+      $0 mocha $spec_file || echo -e "=== ${RED}FAIL${RESET_COLOR} ==="
+    fi
 
     eval "$(bash_setup setup_traps)"
     setup_traps
@@ -466,55 +481,20 @@ case "$action" in
           exec $0 ${script_args[@]}
         fi
 
-        if [[ "$file" =~ ".styl" ]]; then
-          bin/megauni stylus "$path"
-        fi
-
-        if [[ ! -f logs/rendering ]]; then # ========
-          if [[ "$file" =~ "markup.rb" ]]; then
-            bin/megauni render "$path" || rb_failed="$path"
-          else
-            # Most likely a base file, so all files have to be re-rendered:
-            if [[ "$path" =~ "applets" && "$path" =~ ".rb" ]]; then
-              render_all
-            fi
-          fi
-
-          if [[ "$file" =~ "markup.html" ]]; then
-            bin/megauni restart
-          fi
-
-        fi # if ! -f logs/rendering =================
-
         if [[ "$file" == *.js ]]; then
           js_pass="true"
           js_setup jshint! $path || js_pass=""
 
-          if [[ -n "$js_pass" && -n "$last_opt" ]]; then
-
-            spec_file=""
-            if [[ "$path" == */specs/*  ]]; then
-              spec_file="$path"
-            else
-              spec_file=$(echo $(dirname $path)/specs/*-${last_opt}.js)
-              if [[ ! -f "$(echo $spec_file | cut -d' ' -f 1)" ]]; then
-                spec_file=$(echo Server/${next_to_last_opt}/specs/*-${last_opt}.js);
-                if [[ ! -f "$(echo $spec_file | cut -d' ' -f 1)" ]]; then
-                  spec_file=''
-                fi
-              fi
-            fi
-
-            if [[ -n "$spec_file" ]]; then
+          if [[ -n "$js_pass" ]]; then
+            if [[  -n "$spec_file" ]]; then
               $0 mocha $spec_file || echo -e "=== ${RED}FAIL${RESET_COLOR} ==="
             fi
+            if [[ -n "$use_server" ]]; then
+              bin/megauni restart
+            fi
+          fi # === if $js_pass
 
-          fi
-
-          if [[ -n $js_pass && -n "$use_server" ]]; then
-            bin/megauni restart
-          fi
-        fi
+        fi # === if $file == *.js
 
       fi
 
